export const categoriesServices = [
    {
        id: 1,
        title: "General Accounting",
        items: [
            "Accounting",
            "Bookkeeping",
            "Business Accounting",
            "Card Processing",
            "EPOS",
            "Invoice Finance",
            "Tax",
            "Business Financial Planning",
            "Valuations",
            "Budgeting and Forecasting"
        ]
    },
    {
        id: 2,
        title: "Designs and Branding",
        items: [
            "3D Modeling and CAD ",
            "Advert Design",
            "Animation",
            "Binding",
            "Brand Design",
            "Brochure Design",
            "Business Card Design",
            "Product Design",
            "Email Template Design",
            "Engineering and Technical Design",
            "Engineering Design",
            "Flyer & Leaflet Design",
            "Graphic Design",
            "Illustrators",
            "Logo Design",
            "Office Stationery",
            "Packaging Design",
            "Presentation Design",
            "Print Design",
            "Technical Design",
            "Packaging Production",
            "Prototype Design",
            "Infographics",
            "Flyer Design"
        ]
    },
    {
        id: 3,
        title: "Development and Software",
        items: [
            "AI Development",
            "Coding Tuition",
            "Database Development",
            "General Software Development",
            "Mobile Software Development",
            "Software Testing",
            "Web Development",
            "Social Media Marketing",
            "SEO",
            "Search Engine Optimisation",
            "Network, Database and IT Support",
            "Web Design",
            "UX & UI Design",
            "E - Commerce",
            "Managed IT ",
            "Email Marketing"
        ]
    },
    {
        id: 4,
        title: "Entertainment",
        items: [
            "Musician",
            "DJ",
            "Band Entertainment",
            "Composers",
            "Music Band",
            "R and B Entertainment",
            "Blues Band Entertainment",
            "Pop Band Entertainment",
            "Solo Musician Entertainment",
            "Hip Hop Performers",
            "Brass Band Entertainment",
            "Reggae Band Entertainment",
            "Event Planners",
            "MC and Hosts",
            "Circus Acting",
            "Storytellers",
            "Clown Entertainment",
            "Comedians",
            "Face Painting",
            "Classical Music",
            "Corporate Event Entertainment"
        ]
    },
    {
        id: 5,
        title: "Production & Events",
        items: [
            "Actor",
            "Aerial & Drone Photography",
            "Architectural Photography",
            "Audio Production Specialists",
            "AV Equipment Rental for Events",
            "Photographer",
            "Commercial Photographer",
            "Corporate Photographer",
            "Videography",
            "Craft Party Planning",
            "Event Photography",
            "Event Planner",
            "Party Planner",
            "Event Decorator",
            "Staging and Trussing",
            "Video Design & Production",
            "Video Editing",
            "Wedding Decorating",
            "Wedding Photography",
            "Wedding Planning",
            "Models",
            "Catering",
            "Explainer Video",
            "Training Video Production",
            "Promotional Video Production",
            "Commercial Catering"
        ]
    },
    {
        id: 6,
        title: "Advertising and Media",
        items: [
            "Advertising",
            "Advertising Copywriting",
            "Online Media Buying",
            "Print Media Purchasing",
            "Radio Airtime Purchasing",
            "Digital Media",
            "TV Advertising",
            "Freelance Journalists",
            "Press Release Creation",
            "Marketing"
        ]
    },
    {
        id: 7,
        title: "Education & Academics",
        items: [
            "Entrance Exams Tutoring",
            "Biology Tutoring",
            "Calculus Tutoring",
            "Chemistry Tutoring",
            "Economics Tutoring",
            "Electrical Engineering Tutoring",
            "Engineering Tutoring",
            "Environmental Science Tutoring",
            "Geography Tutoring",
            "German Lesson For Adults",
            "GRE Tutoring",
            "History Tutoring",
            "Jobs Entrance Exam Tutoring",
            "Language Tutoring",
            "Maths Tutoring",
            "MCAT Tutoring",
            "Mechanical Engineering Tutoring",
            "Philosophy Tutoring",
            "Physics Tutoring",
            "Poetry Lesson",
            "Precalculus Tutoring",
            "Psychology Tutoring",
            "Reading and Writing Tutoring",
            "SAT Tutoring",
            "Science Tutoring",
            "Statistics Tutoring",
            "TOEFL",
            "Tutoring"
        ]
    },
    {
        id: 8,
        title: "Specialist Tradesmen",
        items: [
            "Blacksmithing",
            "Brick & Stone Cleaning",
            "Bricklayer",
            "Chimney Cleaning",
            "Damp Proofing",
            "Demolition",
            "Mould Inspection & Remediation",
            "Furniture Restoration",
            "Asbestos Removal",
            "Soundproofing",
            "Waste Management",
            "Water Damage Cleanup",
            "Sawmilling",
            "Roof Installation",
            "Painting",
            "Interior Plastering",
            "Weatherproofing"
        ]
    },
    {
        id: 9,
        title: "Training",
        items: [
            "Accounting Training",
            "Adult Basic Education Tutoring",
            "AI Training",
            "Business & Career Coaching",
            "Business Finance Training",
            "Computer Lesson",
            "Construction Safety Training",
            "Cosmetology Training",
            "Leadership Development Training",
            "Legal Training",
            "Makeup Artistry Lesson",
            "Marketing Training",
            "Medical Coding Training",
            "Modeling Lesson",
            "Music Teacher Training",
            "Public Speaking Lesson",
            "Sales Training",
            "Search Engine Optimisation Training",
            "Sign Language Lesson",
            "Social Security Advice and Consultation",
            "Speech & Language Therapy",
            "Study Skills Training",
            "Teacher Training",
            "Typing Training"
        ]
    },
    {
        id: 10,
        title: "Arts Lesson",
        items: [
            "Accordion Lesson",
            "Acting Classes",
            "Bagpipe Lesson",
            "Ballroom Dance Classes",
            "Banjo Lesson",
            "Bass Guitar Lesson",
            "Bassoon Lesson",
            "Belly Dance Lesson",
            "Cello Lesson",
            "Circus Arts Lesson",
            "Clarinet Lesson",
            "Comedy Lesson",
            "Dance Choreography Lesson",
            "Dance Lesson",
            "Double Bass Lesson",
            "Drum Lesson",
            "Fiddle Lesson",
            "Flute Lesson",
            "French Horn Lesson",
            "Guitar Lesson",
            "Harmonica Lesson",
            "Harp Lesson ",
            "Hip Hop Dance Classes",
            "Keyboard Lesson",
            "Mandolin Lesson",
            "Music Composition Lesson",
            "Music Lesson",
            "Music Theory Lesson",
            "Oboe Lesson",
            "Piano Lesson",
            "Pole Dancing Classes",
            "Rap Music Lesson",
            "Salsa Dance Lesson",
            "Saxophone Lesson",
            "Singing Lesson",
            "Tango Dance Lesson",
            "Tap Dance Lesson",
            "Trombone Lesson",
            "Trumpet Lesson",
            "Ukulele Lesson",
            "Viola Lesson",
            "Violin Lesson"
        ]
    },
    {
        id: 11,
        title: "Health and Wellness",
        items: [
            "Acupuncture",
            "Acupressure",
            "Addiction Therapy",
            "Counselling",
            "Alternative Healing",
            "Aromatherapy",
            "Art Therapy",
            "Beauticians",
            "Bereavement Counselling",
            "Cancer Counselling",
            "Child Counselling",
            "Chiropractor",
            "Cognitive Behaviour Therapy",
            "Comfort Pets",
            "Complementary Therapy",
            "Couples Counselling",
            "Dentists",
            "Depression Counselling",
            "Dynamic Interpersonal Therapy",
            "Employee Assistance Programmes",
            "Family Counselling",
            "Gambling Therapy",
            "Hair Loss Treatment",
            "Hearing Aids",
            "Laser Eye Surgery",
            "Life Coaching",
            "Massage Therapy",
            "Neurodiversity Testing",
            "Nutritionists",
            "Dietitians",
            "Physical Therapy",
            "Post Natal Depression",
            "Private Doctors",
            "Private Psychiatry",
            "Psychologists",
            "Psychotherapy",
            "Relationship Counselling",
            "Stylists",
            "Therapist",
            "Relationship ",
            "Marriage Counselling"
        ]
    },
    {
        id: 12,
        title: "Artisans & Repair",
        items: [
            "Air Conditioning Installation",
            "Air Conditioning Repair",
            "Boiler Installation",
            "Boiler Repair & Maintenance",
            "Dishwasher Repair",
            "Fan Installation",
            "Water Heater Installation",
            "Water Heater Maintenance",
            "General Plumbing",
            "Gas Safety Check",
            "Phone Repair",
            "Camera Installation",
            "Vacuum Cleaner Repair",
            "TV & AV Repair",
            "Medical Equipment Repair",
            "Bricklayer",
            "Carpenter",
            "Mobile Phone Unlocking",
            "Pressure Washer Repair",
            "Bathroom Repair",
            "Water Heater Installation",
            "Washing Machine Installation",
            "Borehole",
            "Architectural",
            "General Surveyor",
            "Quantity Surveyor",
            "Property Extensions",
            "Structural Engineer",
            "General Builders",
            "Foundation ",
            "Concrete Installation",
            "Painting",
            "Furniture Making",
            "Asphalt Installation",
            "Building Repair",
            "Security Fence Installation",
            "Gate Installation",
            "Wallpapering",
            "Paint Removal",
            "Interior Decorator",
            "Welding"
        ]
    },
    {
        id: 13,
        title: "Copywriting",
        items: [
            "Advertising Copywriting",
            "Articles and Report Writing",
            "Brochure Copywriting",
            "Case Study Copywriting",
            "Email Copywriting",
            "Marketing Copywriting",
            "PPC Advert Copywriting",
            "Script Writing ",
            "SEO Copywriting and Content",
            "Website Copywriting",
            "User Documentation",
            "Songwriting"
        ]
    },
    {
        id: 14,
        title: "Gardening & Landscaping",
        items: [
            "Artificial Grass Installation",
            "Fertilising",
            "Gardening",
            "Garden Clearance",
            "Grass Cutting",
            "Landscaping",
            "Landscape Design",
            "Lawn Care",
            "Pond Installation",
            "Snow Ploughing",
            "Security Fence Installation",
            "Wildlife Control"
        ]
    },
    {
        id: 15,
        title: "Language Classes",
        items: [
            "Arabic Classes",
            "Chinese Lesson",
            "Dutch Lesson",
            "English Lesson",
            "French Lesson",
            "German Lesson",
            "Italian Lesson",
            "Japanese Lesson",
            "Portuguese Lesson",
            "Russian Lesson",
            "Spanish Lesson",
            "Turkish Lesson",
            "Transcription",
            "Translation"
        ]
    },
    {
        id: 16,
        title: "Recreational Lesson",
        items: [
            "Badminton Lesson",
            "Chess Lesson",
            "Basketball Lesson",
            "Baseball Lesson",
            "Fishing Lesson",
            "Football Coaching",
            "Tennis Lesson",
            "Gymnastics Classes",
            "Swimming Lesson",
            "Volleyball Lesson",
            "Martial Arts Classes",
            "Yoga Classes"
        ]
    },
    {
        id: 17,
        title: "Domestic Cleaning",
        items: [
            "House Cleaning",
            "Office Cleaning",
            "Oven Cleaning",
            "Ironing",
            "Carpet Cleaning",
            "Chimney Cleaning",
            "Rug Cleaning",
            "Window Cleaners"
        ]
    },
    {
        id: 18,
        title: "Commercial Cleaning",
        items: [
            "Office Cleaning",
            "Warehouse Cleaning",
            "End of Tenancy Cleaning"
        ]
    },
    {
        id: 19,
        title: "Crafts",
        items: [
            "Artists",
            "CNC Machine",
            "Dressmakers",
            "Electroplating",
            "Fashion Designer",
            "Florists",
            "Illustrators",
            "Luggage & Bag Makers",
            "Music Engraving",
            "Plastic Fabrication",
            "Portrait Artistry",
            "Powder Coating"
        ]
    },
    {
        id: 20,
        title: "Care",
        items: [
            "Domiciliary Care",
            "Home Care",
            "Adult Care",
            "Child Minding",
            "Baby Sitting"
        ]
    },
    {
        id: 21,
        title: "Legal",
        items: [
            "Tax Lawyer",
            "Immigration Lawyer",
            "Criminal Lawyer",
            "Property Lawer",
            "International Lawer",
            "Commercial Law",
            "Trademark Lawyer",
            "Debt Recovery",
            "Intellectual Property Lawyer",
            "Licensing"
        ]
    },
    {
        id: 22,
        title: "Pet",
        items: [
            "Dog & Pet Grooming",
            "Dog Training",
            "Dog Walking",
            "Farriers",
            "Kennels",
            "Livery Yards and Stables",
            "Pet Care",
            "Pet Funerals and Cremations",
            "Pet Sitting",
            "Pet Trainers",
            "Vets",
            "Pest Control"
        ]
    },
    {
        id: 23,
        title: "Security",
        items: [
            "Network Security",
            "Overall System Security",
            "Data backup",
            "Data Destruction",
            "Database security",
            "Cybersecurity"
        ]
    },
    {
        id: 24,
        title: "Delivery and Movement",
        items: [
            "Property Moving",
            "Logistics",
            "Delivery",
            "Courier",
            "Relocation Consultants"
        ]
    },
    {
        id: 25,
        title: "Personal",
        items: [
            "Bodyguard",
            "Personal Chef",
            "Palm Reading",
            "Psychologists",
            "Mediation",
            "Private Investigators"
        ]
    },
    {
        id: 26,
        title: "Telecommunication",
        items: [
            "Internet  Provider",
            "Video Conferencing",
            "Leased Lines"
        ]
    },
    {
        id: 27,
        title: "Insurance",
        items: [
            "Car Insurance",
            "Life Insurance",
            "Stock Insurance",
            "Insurer",
            "Health Insurance"
        ]
    },
    {
        id: 28,
        title: "Weddings",
        items: [
            "Bridesmaids & Groomsmen",
            "Wedding Hairstylist",
            "Wedding Makeup",
            "Wedding Jewellery",
            "Wedding Catering",
            "Marquee Hire",
            "Wedding Stylist",
            "Wedding Venues",
            "Wedding Photographer",
            "Wedding Music Band",
            "Wedding Planner",
            "Wedding MC",
            "Wedding DJ",
            "Wedding Cakes"
        ]
    },
    {
        id: 29,
        title: "Fashion & Beauty",
        items: [
            "Branded Clothing",
            "Tattoo Removal",
            "Tattoo Artist",
            "Laser Hair Removal",
            "Hair Transplants",
            "Hair Extensions"
        ]
    },
    {
        id: 30,
        title: "Printing Services",
        items: [
            "Branded Clothing",
            "Brochure Printing",
            "Business Card Printing",
            "Canvas Printing",
            "General Printing",
            "Leaflet Printing",
            "NCR Printing",
            "Office Stationery",
            "Postcard Printing",
            "Poster Printing",
            "Screen Printing",
            "Spot Colour Printing",
            "T - shirt Printing",
            "Clothes Printing"
        ]
    },
]