export const leadsData = [
    {
        id: 1,
        username: "@jewella",
        userDisplayName: "jewella",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "house cleaning",
        location: "london, ub2",
        date: "22/08/2024",
        time: "06:30 AM",
        pendingResponse: 2,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "jewlla@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 2,
        username: "@cynthia",
        userDisplayName: "cynthia",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "mechanic",
        location: "Usa, ub2",
        date: "22/03/2024",
        time: "08:30 AM",
        pendingResponse: 2,
        totalResponse: 3,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "cynthia@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 3,
        username: "@pamela",
        userDisplayName: "pamela",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "washin cars",
        location: "london, ub2",
        date: "21/12/2024",
        time: "04:30 AM",
        pendingResponse: 1,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "pamela@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 4,
        username: "@anita",
        userDisplayName: "anita",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "Nanny",
        location: "london, ub2",
        date: "01/04/2024",
        time: "09:40 AM",
        pendingResponse: 3,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "anita@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 5,
        username: "@edwart",
        userDisplayName: "edwart",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "laundry",
        location: "london, ub2",
        date: "04/04/2024",
        time: "02:40 PM",
        pendingResponse: 1,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "edwart@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 6,
        username: "@frank",
        userDisplayName: "frank",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "house cleaning",
        location: "london, ub2",
        date: "04/11/2024",
        time: "12:40 PM",
        pendingResponse: 2,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "frank@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 7,
        username: "@jewella",
        userDisplayName: "jewella",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "house cleaning",
        location: "london, ub2",
        date: "22/08/2024",
        time: "06:30 AM",
        pendingResponse: 2,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "jewlla@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 8,
        username: "@cynthia",
        userDisplayName: "cynthia",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "mechanic",
        location: "london, ub2",
        date: "22/03/2024",
        time: "08:30 AM",
        pendingResponse: 2,
        totalResponse: 3,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "cynthia@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 9,
        username: "@pamela",
        userDisplayName: "pamela",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "washin cars",
        location: "london, ub2",
        date: "21/12/2024",
        time: "04:30 AM",
        pendingResponse: 1,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "pamela@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 10,
        username: "@anita",
        userDisplayName: "anita",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "Nanny",
        location: "london, ub2",
        date: "01/04/2024",
        time: "09:40 AM",
        pendingResponse: 3,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "anita@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 11,
        username: "@edwart",
        userDisplayName: "edwart",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "laundry",
        location: "london, ub2",
        date: "04/04/2024",
        time: "02:40 PM",
        pendingResponse: 1,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "edwart@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    },
    {
        id: 12,
        username: "@frank",
        userDisplayName: "frank",
        userPhoto: "https://www.cancer.gov/sites/g/files/xnrzdm211/files/styles/cgov_social_media/public/cgov_image/media_image/2023-07/Brunilde%20M.%20Gril%20_MVN9418%20crop%20New.jpg",
        projectTitle: "house cleaning",
        location: "london, ub2",
        date: "04/11/2024",
        time: "12:40 PM",
        pendingResponse: 2,
        totalResponse: 4,
        projectDescription: "We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users interested in fashion apparel. We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users . We will be developing a modern e-commerce website aimed at providing a seamless shopping experience for users ",
        userPhoneNumber: 4480123456,
        userEmail: "frank@gmail.com",
        status: "pending",
        performanceType: "Bands / Musicians / Singers",
        performanceSide: "Indoor & Outdoor",
        typeOfEvent: "Birthday party - child",
        budget: {
            budgetTitle: "Premium Project",
            budgetAmount: "£3,000 & above"
        }
    }
]